//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace install.FBAMembershipService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="FBAMembershipService.IFBAUser")]
    public interface IFBAUser {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFBAUser/AddUser", ReplyAction="http://tempuri.org/IFBAUser/AddUserResponse")]
        string AddUser(string userName, string email, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFBAUser/AddUser", ReplyAction="http://tempuri.org/IFBAUser/AddUserResponse")]
        System.Threading.Tasks.Task<string> AddUserAsync(string userName, string email, string password);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IFBAUserChannel : install.FBAMembershipService.IFBAUser, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FBAUserClient : System.ServiceModel.ClientBase<install.FBAMembershipService.IFBAUser>, install.FBAMembershipService.IFBAUser {
        
        public FBAUserClient() {
        }
        
        public FBAUserClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FBAUserClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FBAUserClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FBAUserClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string AddUser(string userName, string email, string password) {
            return base.Channel.AddUser(userName, email, password);
        }
        
        public System.Threading.Tasks.Task<string> AddUserAsync(string userName, string email, string password) {
            return base.Channel.AddUserAsync(userName, email, password);
        }
    }
}
