//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace control.SharePointService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SharePointService.ISharePoint")]
    public interface ISharePoint {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISharePoint/CreateSPSiteCollection", ReplyAction="http://tempuri.org/ISharePoint/CreateSPSiteCollectionResponse")]
        string CreateSPSiteCollection(string appName, string dnsName, string webTemplate, string fbaAdminName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISharePoint/CreateSPSiteCollection", ReplyAction="http://tempuri.org/ISharePoint/CreateSPSiteCollectionResponse")]
        System.Threading.Tasks.Task<string> CreateSPSiteCollectionAsync(string appName, string dnsName, string webTemplate, string fbaAdminName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISharePoint/CreateSPSiteCollectionAsynchronous", ReplyAction="http://tempuri.org/ISharePoint/CreateSPSiteCollectionAsynchronousResponse")]
        string CreateSPSiteCollectionAsynchronous(string appName, string dnsName, string webTemplate, string fbaAdminName, string fbaAdminPwd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISharePoint/CreateSPSiteCollectionAsynchronous", ReplyAction="http://tempuri.org/ISharePoint/CreateSPSiteCollectionAsynchronousResponse")]
        System.Threading.Tasks.Task<string> CreateSPSiteCollectionAsynchronousAsync(string appName, string dnsName, string webTemplate, string fbaAdminName, string fbaAdminPwd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISharePoint/DeleteSPSiteCollection", ReplyAction="http://tempuri.org/ISharePoint/DeleteSPSiteCollectionResponse")]
        string DeleteSPSiteCollection(string dnsName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISharePoint/DeleteSPSiteCollection", ReplyAction="http://tempuri.org/ISharePoint/DeleteSPSiteCollectionResponse")]
        System.Threading.Tasks.Task<string> DeleteSPSiteCollectionAsync(string dnsName);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISharePointChannel : control.SharePointService.ISharePoint, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SharePointClient : System.ServiceModel.ClientBase<control.SharePointService.ISharePoint>, control.SharePointService.ISharePoint {
        
        public SharePointClient() {
        }
        
        public SharePointClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SharePointClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SharePointClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SharePointClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string CreateSPSiteCollection(string appName, string dnsName, string webTemplate, string fbaAdminName) {
            return base.Channel.CreateSPSiteCollection(appName, dnsName, webTemplate, fbaAdminName);
        }
        
        public System.Threading.Tasks.Task<string> CreateSPSiteCollectionAsync(string appName, string dnsName, string webTemplate, string fbaAdminName) {
            return base.Channel.CreateSPSiteCollectionAsync(appName, dnsName, webTemplate, fbaAdminName);
        }
        
        public string CreateSPSiteCollectionAsynchronous(string appName, string dnsName, string webTemplate, string fbaAdminName, string fbaAdminPwd) {
            return base.Channel.CreateSPSiteCollectionAsynchronous(appName, dnsName, webTemplate, fbaAdminName, fbaAdminPwd);
        }
        
        public System.Threading.Tasks.Task<string> CreateSPSiteCollectionAsynchronousAsync(string appName, string dnsName, string webTemplate, string fbaAdminName, string fbaAdminPwd) {
            return base.Channel.CreateSPSiteCollectionAsynchronousAsync(appName, dnsName, webTemplate, fbaAdminName, fbaAdminPwd);
        }
        
        public string DeleteSPSiteCollection(string dnsName) {
            return base.Channel.DeleteSPSiteCollection(dnsName);
        }
        
        public System.Threading.Tasks.Task<string> DeleteSPSiteCollectionAsync(string dnsName) {
            return base.Channel.DeleteSPSiteCollectionAsync(dnsName);
        }
    }
}
