//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace install.SharePointService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SharePointService.ISharePoint")]
    public interface ISharePoint {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISharePoint/CreateSPSiteCollection", ReplyAction="http://tempuri.org/ISharePoint/CreateSPSiteCollectionResponse")]
        string CreateSPSiteCollection(string appName, string dnsName, string webTemplate, string fbaAdminName);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/ISharePoint/CreateSPSiteCollection", ReplyAction="http://tempuri.org/ISharePoint/CreateSPSiteCollectionResponse")]
        System.IAsyncResult BeginCreateSPSiteCollection(string appName, string dnsName, string webTemplate, string fbaAdminName, System.AsyncCallback callback, object asyncState);
        
        string EndCreateSPSiteCollection(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISharePoint/CreateSPSiteCollectionAsynchronous", ReplyAction="http://tempuri.org/ISharePoint/CreateSPSiteCollectionAsynchronousResponse")]
        string CreateSPSiteCollectionAsynchronous(string appName, string dnsName, string webTemplate, string fbaAdminName, string fbaAdminPwd);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/ISharePoint/CreateSPSiteCollectionAsynchronous", ReplyAction="http://tempuri.org/ISharePoint/CreateSPSiteCollectionAsynchronousResponse")]
        System.IAsyncResult BeginCreateSPSiteCollectionAsynchronous(string appName, string dnsName, string webTemplate, string fbaAdminName, string fbaAdminPwd, System.AsyncCallback callback, object asyncState);
        
        string EndCreateSPSiteCollectionAsynchronous(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISharePointChannel : install.SharePointService.ISharePoint, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CreateSPSiteCollectionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public CreateSPSiteCollectionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CreateSPSiteCollectionAsynchronousCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public CreateSPSiteCollectionAsynchronousCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SharePointClient : System.ServiceModel.ClientBase<install.SharePointService.ISharePoint>, install.SharePointService.ISharePoint {
        
        private BeginOperationDelegate onBeginCreateSPSiteCollectionDelegate;
        
        private EndOperationDelegate onEndCreateSPSiteCollectionDelegate;
        
        private System.Threading.SendOrPostCallback onCreateSPSiteCollectionCompletedDelegate;
        
        private BeginOperationDelegate onBeginCreateSPSiteCollectionAsynchronousDelegate;
        
        private EndOperationDelegate onEndCreateSPSiteCollectionAsynchronousDelegate;
        
        private System.Threading.SendOrPostCallback onCreateSPSiteCollectionAsynchronousCompletedDelegate;
        
        public SharePointClient() {
        }
        
        public SharePointClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SharePointClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SharePointClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SharePointClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public event System.EventHandler<CreateSPSiteCollectionCompletedEventArgs> CreateSPSiteCollectionCompleted;
        
        public event System.EventHandler<CreateSPSiteCollectionAsynchronousCompletedEventArgs> CreateSPSiteCollectionAsynchronousCompleted;
        
        public string CreateSPSiteCollection(string appName, string dnsName, string webTemplate, string fbaAdminName) {
            return base.Channel.CreateSPSiteCollection(appName, dnsName, webTemplate, fbaAdminName);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginCreateSPSiteCollection(string appName, string dnsName, string webTemplate, string fbaAdminName, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginCreateSPSiteCollection(appName, dnsName, webTemplate, fbaAdminName, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public string EndCreateSPSiteCollection(System.IAsyncResult result) {
            return base.Channel.EndCreateSPSiteCollection(result);
        }
        
        private System.IAsyncResult OnBeginCreateSPSiteCollection(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string appName = ((string)(inValues[0]));
            string dnsName = ((string)(inValues[1]));
            string webTemplate = ((string)(inValues[2]));
            string fbaAdminName = ((string)(inValues[3]));
            return this.BeginCreateSPSiteCollection(appName, dnsName, webTemplate, fbaAdminName, callback, asyncState);
        }
        
        private object[] OnEndCreateSPSiteCollection(System.IAsyncResult result) {
            string retVal = this.EndCreateSPSiteCollection(result);
            return new object[] {
                    retVal};
        }
        
        private void OnCreateSPSiteCollectionCompleted(object state) {
            if ((this.CreateSPSiteCollectionCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CreateSPSiteCollectionCompleted(this, new CreateSPSiteCollectionCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CreateSPSiteCollectionAsync(string appName, string dnsName, string webTemplate, string fbaAdminName) {
            this.CreateSPSiteCollectionAsync(appName, dnsName, webTemplate, fbaAdminName, null);
        }
        
        public void CreateSPSiteCollectionAsync(string appName, string dnsName, string webTemplate, string fbaAdminName, object userState) {
            if ((this.onBeginCreateSPSiteCollectionDelegate == null)) {
                this.onBeginCreateSPSiteCollectionDelegate = new BeginOperationDelegate(this.OnBeginCreateSPSiteCollection);
            }
            if ((this.onEndCreateSPSiteCollectionDelegate == null)) {
                this.onEndCreateSPSiteCollectionDelegate = new EndOperationDelegate(this.OnEndCreateSPSiteCollection);
            }
            if ((this.onCreateSPSiteCollectionCompletedDelegate == null)) {
                this.onCreateSPSiteCollectionCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCreateSPSiteCollectionCompleted);
            }
            base.InvokeAsync(this.onBeginCreateSPSiteCollectionDelegate, new object[] {
                        appName,
                        dnsName,
                        webTemplate,
                        fbaAdminName}, this.onEndCreateSPSiteCollectionDelegate, this.onCreateSPSiteCollectionCompletedDelegate, userState);
        }
        
        public string CreateSPSiteCollectionAsynchronous(string appName, string dnsName, string webTemplate, string fbaAdminName, string fbaAdminPwd) {
            return base.Channel.CreateSPSiteCollectionAsynchronous(appName, dnsName, webTemplate, fbaAdminName, fbaAdminPwd);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginCreateSPSiteCollectionAsynchronous(string appName, string dnsName, string webTemplate, string fbaAdminName, string fbaAdminPwd, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginCreateSPSiteCollectionAsynchronous(appName, dnsName, webTemplate, fbaAdminName, fbaAdminPwd, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public string EndCreateSPSiteCollectionAsynchronous(System.IAsyncResult result) {
            return base.Channel.EndCreateSPSiteCollectionAsynchronous(result);
        }
        
        private System.IAsyncResult OnBeginCreateSPSiteCollectionAsynchronous(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string appName = ((string)(inValues[0]));
            string dnsName = ((string)(inValues[1]));
            string webTemplate = ((string)(inValues[2]));
            string fbaAdminName = ((string)(inValues[3]));
            string fbaAdminPwd = ((string)(inValues[4]));
            return this.BeginCreateSPSiteCollectionAsynchronous(appName, dnsName, webTemplate, fbaAdminName, fbaAdminPwd, callback, asyncState);
        }
        
        private object[] OnEndCreateSPSiteCollectionAsynchronous(System.IAsyncResult result) {
            string retVal = this.EndCreateSPSiteCollectionAsynchronous(result);
            return new object[] {
                    retVal};
        }
        
        private void OnCreateSPSiteCollectionAsynchronousCompleted(object state) {
            if ((this.CreateSPSiteCollectionAsynchronousCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CreateSPSiteCollectionAsynchronousCompleted(this, new CreateSPSiteCollectionAsynchronousCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CreateSPSiteCollectionAsynchronousAsync(string appName, string dnsName, string webTemplate, string fbaAdminName, string fbaAdminPwd) {
            this.CreateSPSiteCollectionAsynchronousAsync(appName, dnsName, webTemplate, fbaAdminName, fbaAdminPwd, null);
        }
        
        public void CreateSPSiteCollectionAsynchronousAsync(string appName, string dnsName, string webTemplate, string fbaAdminName, string fbaAdminPwd, object userState) {
            if ((this.onBeginCreateSPSiteCollectionAsynchronousDelegate == null)) {
                this.onBeginCreateSPSiteCollectionAsynchronousDelegate = new BeginOperationDelegate(this.OnBeginCreateSPSiteCollectionAsynchronous);
            }
            if ((this.onEndCreateSPSiteCollectionAsynchronousDelegate == null)) {
                this.onEndCreateSPSiteCollectionAsynchronousDelegate = new EndOperationDelegate(this.OnEndCreateSPSiteCollectionAsynchronous);
            }
            if ((this.onCreateSPSiteCollectionAsynchronousCompletedDelegate == null)) {
                this.onCreateSPSiteCollectionAsynchronousCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCreateSPSiteCollectionAsynchronousCompleted);
            }
            base.InvokeAsync(this.onBeginCreateSPSiteCollectionAsynchronousDelegate, new object[] {
                        appName,
                        dnsName,
                        webTemplate,
                        fbaAdminName,
                        fbaAdminPwd}, this.onEndCreateSPSiteCollectionAsynchronousDelegate, this.onCreateSPSiteCollectionAsynchronousCompletedDelegate, userState);
        }
    }
}
